### ISSUE TITLE
Conda build failing

### ISSUE THREAD

**Issue by xmnlab** [arxlang/arxcpp#9]
https://github.com/arx-org/arx/pull/8/checks#step:4:1698

FAILED: CMakeFiles/arx.dir/arx/src/arx.cpp.o 
$PREFIX/bin/clang++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I$SRC_DIR/arx/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/arx-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -MD -MT CMakeFiles/arx.dir/arx/src/arx.cpp.o -MF CMakeFiles/arx.dir/arx/src/arx.cpp.o.d -o CMakeFiles/arx.dir/arx/src/arx.cpp.o -c $SRC_DIR/arx/src/arx.cpp
In file included from $SRC_DIR/arx/src/arx.cpp:4:
In file included from $PREFIX/include/arrow/api.h:22:
In file included from $PREFIX/include/arrow/array.h:37:
$PREFIX/include/arrow/array/array_base.h:20:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 205, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 105, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 164, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2211, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/staged-recipes/build_artifacts/arx_1646973231952/work/conda_build.sh']' returned non-zero exit status 1.
valid configs are {'win64', 'linux64_cuda110', 'linux64_cuda102', 'osx64', 'linux64', 'linux64_cuda112', 'linux64_cuda111'}
Using linux64 configuration
Traceback (most recent call last):
  File "/tmp/staged-recipes/build-locally.py", line 101, in <module>
    main()
  File "/tmp/staged-recipes/build-locally.py", line 95, in main
    run_docker_build(ns)
  File "/tmp/staged-recipes/build-locally.py", line 33, in run_docker_build
    subprocess.check_call([script])
  File "/usr/share/miniconda/envs/arx-build/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
make: *** [Makefile:78: conda-build] Error 1
Error: Process completed with exit code 2.

**Comment by xmnlab** [comment]
conda build meta:

https://github.com/arx-org/arx/blob/main/conda/build/meta.yaml

**Comment by xmnlab** [comment]
for now it is using gcc/g++ instead of clang/clang++ and it is working. 
it would be great to move it to clang
